// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	beans "github.com/bradenrayhorn/beans/beans"

	mock "github.com/stretchr/testify/mock"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, name, budgetID
func (_m *AccountService) Create(ctx context.Context, name beans.Name, budgetID beans.ID) (*beans.Account, error) {
	ret := _m.Called(ctx, name, budgetID)

	var r0 *beans.Account
	if rf, ok := ret.Get(0).(func(context.Context, beans.Name, beans.ID) *beans.Account); ok {
		r0 = rf(ctx, name, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*beans.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, beans.Name, beans.ID) error); ok {
		r1 = rf(ctx, name, budgetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountService(t mockConstructorTestingTNewAccountService) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
