// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	beans "github.com/bradenrayhorn/beans/beans"

	mock "github.com/stretchr/testify/mock"
)

// BudgetService is an autogenerated mock type for the BudgetService type
type BudgetService struct {
	mock.Mock
}

// CreateBudget provides a mock function with given fields: ctx, name, userID
func (_m *BudgetService) CreateBudget(ctx context.Context, name beans.Name, userID beans.UserID) (*beans.Budget, error) {
	ret := _m.Called(ctx, name, userID)

	var r0 *beans.Budget
	if rf, ok := ret.Get(0).(func(context.Context, beans.Name, beans.UserID) *beans.Budget); ok {
		r0 = rf(ctx, name, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*beans.Budget)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, beans.Name, beans.UserID) error); ok {
		r1 = rf(ctx, name, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBudgetService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBudgetService creates a new instance of BudgetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBudgetService(t mockConstructorTestingTNewBudgetService) *BudgetService {
	mock := &BudgetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
