// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	beans "github.com/bradenrayhorn/beans/beans"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, username, password
func (_m *UserService) CreateUser(ctx context.Context, username beans.Username, password beans.Password) (*beans.User, error) {
	ret := _m.Called(ctx, username, password)

	var r0 *beans.User
	if rf, ok := ret.Get(0).(func(context.Context, beans.Username, beans.Password) *beans.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*beans.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, beans.Username, beans.Password) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *UserService) Login(ctx context.Context, username beans.Username, password beans.Password) (*beans.User, error) {
	ret := _m.Called(ctx, username, password)

	var r0 *beans.User
	if rf, ok := ret.Get(0).(func(context.Context, beans.Username, beans.Password) *beans.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*beans.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, beans.Username, beans.Password) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserService(t mockConstructorTestingTNewUserService) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
