version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "server/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "ui/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
        update-types:
          - "major"
      eslint:
        patterns:
          - "eslint*"
        update-types:
          - "major"
      prettier:
        patterns:
          - "prettier*"
        update-types:
          - "major"
    ignore:
      # Ignore major updates for @types/node, will update manually
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"


