import { Button, Container, FormControl, FormLabel, Heading, Input, VStack } from '@chakra-ui/react'
import PageCard from 'components/PageCard'
import type { NextPage } from 'next'
import Head from 'next/head'

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container mt={4}>
          <Heading>Log in to beans</Heading>
          <PageCard>
            <VStack p={8} mt={4} spacing={6}>
              <FormControl>
                <FormLabel>Username</FormLabel>
                <Input />
              </FormControl>
              <FormControl>
                <FormLabel>Password</FormLabel>
                <Input type="password" />
              </FormControl>
              <Button type="submit" w="full">
                Log in
              </Button>
            </VStack>
          </PageCard>
        </Container>
      </main>
    </>
  )
}

export default Login
