name: beans-local

services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - "UNPROXIED_SERVER_URL=http://server:8080"
      - "ORIGIN=http://localhost:8080"
