CREATE TABLE category_groups (
    id CHAR(27) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_income boolean NOT NULL,
    budget_id CHAR(27) NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE categories (
    id CHAR(27) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    budget_id CHAR(27) NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
    group_id CHAR(27) NOT NULL REFERENCES category_groups(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

