// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        string
	Name      string
	BudgetID  string
	OffBudget bool
	CreatedAt pgtype.Timestamp
}

type Budget struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamp
}

type BudgetsUser struct {
	BudgetID string
	UserID   string
}

type Category struct {
	ID        string
	Name      string
	BudgetID  string
	GroupID   string
	CreatedAt pgtype.Timestamp
}

type CategoryGroup struct {
	ID        string
	Name      string
	IsIncome  bool
	BudgetID  string
	CreatedAt pgtype.Timestamp
}

type Month struct {
	ID        string
	BudgetID  string
	Date      pgtype.Date
	Carryover pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

type MonthCategory struct {
	ID         string
	MonthID    string
	CategoryID string
	Amount     pgtype.Numeric
	CreatedAt  pgtype.Timestamp
}

type Payee struct {
	ID        string
	Name      string
	BudgetID  string
	CreatedAt pgtype.Timestamp
}

type Transaction struct {
	ID         string
	AccountID  string
	PayeeID    pgtype.Text
	CategoryID pgtype.Text
	TransferID pgtype.Text
	Date       pgtype.Date
	Amount     pgtype.Numeric
	Notes      pgtype.Text
	CreatedAt  pgtype.Timestamp
}

type User struct {
	ID        string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
}
