{{- if .Values.litestream.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beans.fullname" . }}-litestream-config
  labels:
    {{- include "beans.labels" . | nindent 4 }}
data:
  litestream.yml: |
    {{- toYaml .Values.litestream.config | nindent 4 }}
{{- end }}
