apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beans.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}
