apiVersion: v1
kind: Service
metadata:
  name: {{ include "beans.fullname" . }}-server
  labels:
    {{- include "beans.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "beans.selectorLabelsServer" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beans.fullname" . }}-ui
  labels:
    {{- include "beans.labelsUI" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "beans.selectorLabelsUI" . | nindent 4 }}
---
