// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: months.sql

package db

import (
	"context"
	"time"
)

const createMonth = `-- name: CreateMonth :exec
INSERT INTO months (
  id, budget_id, date
) VALUES ($1, $2, $3)
`

type CreateMonthParams struct {
	ID       string
	BudgetID string
	Date     time.Time
}

func (q *Queries) CreateMonth(ctx context.Context, arg CreateMonthParams) error {
	_, err := q.db.Exec(ctx, createMonth, arg.ID, arg.BudgetID, arg.Date)
	return err
}
