name: Lint Frontend
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  eslint:
    name: ESLint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./web

      - name: Run lint
        run: npm run lint
        working-directory: ./web

  prettier:
    name: Prettier
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./web

      - name: Run lint
        run: npm run format:lint
        working-directory: ./web
