name: Go

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
          cache: false
      - name: Run tests
        run: "go test -tags test ./..."
