name: Playwright Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test:
    name: Test E2E
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./web
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./web

    - name: Build frontend
      run: npm run build 
      working-directory: ./web

    - name: Docker compose up
      run: docker compose up -d
     
    - name: Run migrations
      run: go run ./cmd/beans migrate

    - name: Run Playwright tests
      run: npm run e2e:ci
      working-directory: ./web

    - name: Docker compose down 
      run: docker compose down -v

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: web/playwright-report/
        retention-days: 30

