name: Playwright Tests
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main, test]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
      working-directory: ./web
    - name: Build
      run: npm run build 
      working-directory: ./web
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./web
    - name: Run Playwright tests
      run: npm run e2e:ci
      working-directory: ./web
    - name: Adding markdown
      run: "if test -f web/playwright-report/index.html; then cat web/playwright-report/index.html >> $GITHUB_STEP_SUMMARY; fi"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: web/playwright-report/
        retention-days: 30

