name: Release

on:
  release:
    types:
      - published

jobs:
  docker:
    name: Retag and push images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Tag and push ui
        run: |
          IMAGE=ghcr.io/bradenrayhorn/beans-ui
          EXISTING_TAG=$IMAGE:next-${{ github.sha }}
          TAG=${{ github.event.release.tag_name }}
          RELEASE_VERSION="${TAG//v/}"

          docker buildx imagetools create \
            --tag $IMAGE:$RELEASE_VERSION \
            --tag $IMAGE:latest \
            $EXISTING_TAG

      - name: Tag and push server
        run: |
          IMAGE=ghcr.io/bradenrayhorn/beans-server
          EXISTING_TAG=$IMAGE:next-${{ github.sha }}
          TAG=${{ github.event.release.tag_name }}
          RELEASE_VERSION="${TAG//v/}"

          docker buildx imagetools create \
            --tag $IMAGE:$RELEASE_VERSION \
            --tag $IMAGE:latest \
            $EXISTING_TAG
